version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: react-widgets
    versions:
    - 4.6.1
    - 5.0.0
    - 5.0.1
    - 5.0.3
    - 5.0.4
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
